export enum BlogActionConstants {
  ADD_BLOG_POST = 'ADD_BLOG_POST',
  DELETE_BLOG_POST = 'DELETE_BLOG_POST',
  UPDATE_BLOG_POST = 'UPDATE_BLOG_POST',
  GET_BLOG_POSTS = 'GET_BLOG_POSTS',
  GET_BLOG_POST = 'GET_BLOG_POST',
}
